# Generated by Django 2.1.4 on 2019-02-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_auto_20190116_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='sellername',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
